[package]
name = "schnorr-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = { version =  "0.4", features = ["rand"] }
num-traits = "0.2"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"  # 可选，用于打印哈希